/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analise;

import bancoDeDados.Dados_BD;
import beneficios_convenios.Beneficio;
import com.sun.javafx.image.impl.IntArgb;
import java.awt.List;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sidimar
 */
public class GerenciaBeneficio extends javax.swing.JFrame {

    DefaultTableModel modelo;
    Beneficio b;
//    String[] linha;

    public GerenciaBeneficio() {
        initComponents();

        montarTabela();
        
        //botoes desabilitados
        jBAtualizar.setEnabled(false);
        jBEditar.setEnabled(false);
        jBExcluir.setEnabled(false);

        //txt desabilitados
        jTTipo.setEnabled(false);
        jTNome.setEnabled(false);
        jTStatus.setEnabled(false);
        jTAcrescimo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jBEditar = new javax.swing.JButton();
        jBAtualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jTStatus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTAcrescimo = new javax.swing.JTextField();
        jTTipo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTid = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Data", "Tipo", "Acrecimo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabela);

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBAtualizar.setText("Atualizar");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });

        jLabel1.setText("Beneficios:");

        jTNome.setEnabled(false);

        jTStatus.setEnabled(false);

        jLabel3.setText("Nome:");

        jLabel4.setText("Data:");

        jLabel2.setText("Tipo:");

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jLabel5.setText("Acrescimo:");

        jTAcrescimo.setEnabled(false);

        jTTipo.setEnabled(false);
        jTTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTipoActionPerformed(evt);
            }
        });

        jLabel6.setText("ID:");

        jTid.setEditable(false);
        jTid.setEnabled(false);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(332, 332, 332)
                                .addComponent(jBAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFechar)
                                .addGap(19, 19, 19)))))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jTAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBExcluir)
                    .addComponent(jBAtualizar)
                    .addComponent(jBEditar)
                    .addComponent(btnFechar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        int linha = jTabela.getSelectedRow();
        Dados_BD dados = new Dados_BD();
        dados.excluir(Integer.parseInt(jTabela.getValueAt(linha, 0).toString()));
//        System.out.println(jTabela.getValueAt(jTabela.getSelectedRow(), 0).toString());

    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jTTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTipoActionPerformed

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed

        if (jTabela.isRowSelected(jTabela.getSelectedRow())) {
            modelo = (DefaultTableModel) jTabela.getModel();
            //String[] linha = new String[6];
            Beneficio bUp = new Beneficio();
            ArrayList<String> dadosBenef = new ArrayList<>();
            String id = jTid.getText();
            String nome = jTNome.getText();
            String data = jTStatus.getText();
            String tipo = jTTipo.getText();
            String acresc = jTAcrescimo.getText();
            dadosBenef.add(id);
            dadosBenef.add(nome);
            dadosBenef.add(data);
            dadosBenef.add(tipo);
            dadosBenef.add(acresc);
            bUp.editar(dadosBenef);

            if (bUp.sucesso() == true) {
                  limpaCampos();
                  montarTabela();
                  jBAtualizar.setEnabled(false);
                  jBEditar.setEnabled(true);
                  jBExcluir.setEnabled(true);
            }

//            linha[1] = jTNome.getText();
//            linha[2] = jTStatus.getText();
//            linha[3] = jTTipo.getText();
//            linha[4] = jTAcrescimo.getText();
//            linha[0] = jTid.getText();
            //linha[5] = jTabela.getValueAt(jTabela.getSelectedRow(), 0).toString();
//            linha[6] = jTabela.getValueAt(jTabela.getSelectedRow(), 0).toString();
            //linha[2] = Double.parseDouble(dadosBebida.get(0).getCodigo()) ;
            // modelo.addRow(linha);
            //        System.out.println(linha[5]);
            //this.limpacampos();
//            b = new Beneficio(linha[1], linha[2], linha[3], linha[4], linha[5]);
            //b.editar();
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum registyo selecionado para edicao");
        }

    }//GEN-LAST:event_jBAtualizarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed

        //os campos de texto estão dsabilitados. Ao clicar em editar, os campos serão habilitados
        //o botao editar e excluir serao desabilitado
        //a edição sera feita e clicar em atualizar para salvar as modificações
        //botoes desabilitados
        jBAtualizar.setEnabled(true);
        jBEditar.setEnabled(false);
        jBExcluir.setEnabled(false);

        //txt desabilitados
        jTTipo.setEnabled(true);
        jTNome.setEnabled(true);
        jTStatus.setEnabled(true);
        jTAcrescimo.setEnabled(true);

    }//GEN-LAST:event_jBEditarActionPerformed

    private void jTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseClicked

        jBAtualizar.setEnabled(false);
        jBEditar.setEnabled(true);
        jBExcluir.setEnabled(true);
        try {
            // jTabela.setCellSelectionEnabled(true);
            int linha = jTabela.getSelectedRow();
            System.out.println("" + linha);
            if (jTabela.isRowSelected(linha)) {
                //
                jTNome.setText(jTabela.getValueAt(linha, 1).toString());
                jTStatus.setText(jTabela.getValueAt(linha, 2).toString());
                jTTipo.setText(jTabela.getValueAt(linha, 3).toString());
                jTAcrescimo.setText(jTabela.getValueAt(linha, 4).toString());
                jTid.setText(jTabela.getValueAt(linha, 0).toString());

            } else {
                System.out.println("nao esta habilitado para edicao");
            }
        } catch (Exception e) {

            System.out.println(e.getCause());
        }

    }//GEN-LAST:event_jTabelaMouseClicked

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaBeneficio().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTAcrescimo;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTStatus;
    private javax.swing.JTextField jTTipo;
    private javax.swing.JTable jTabela;
    private javax.swing.JTextField jTid;
    // End of variables declaration//GEN-END:variables

    public boolean verificaCampos() {
        if (jTNome.getText().isEmpty() || jTStatus.getText().isEmpty() || jTTipo.getText().isEmpty() || jTAcrescimo.getText().isEmpty() || jTid.getText().isEmpty()) {
            return true;//retorna true se algum campo for vazio
        } else {
            return false; //retorna false se todos os campos estiverem preenchidos
        }
    }

    public void limpaCampos() {
        jTNome.setText("");
        jTStatus.setText("");
        jTTipo.setText("");
        jTAcrescimo.setText("");
        jTid.setText("");

    }
    
    public void montarTabela(){
        DefaultTableModel modelo = (DefaultTableModel) jTabela.getModel();
        modelo.setNumRows(0);
        jTabela.setCellSelectionEnabled(false);
        Dados_BD bd = new Dados_BD();
        ResultSet dados;
        try {
            dados = bd.consultar("beneficio");
            while (dados.next()) {
                modelo.addRow(new Object[]{
                    dados.getString(1), dados.getString(2), dados.getString(3), dados.getString(4), dados.getString(5)
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(GerenciaBeneficio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
